### ISSUE TITLE
Yosemite support

### ISSUE THREAD

**Issue by okertanov** [jbtule/cdto#15]
Doesn't work. Silently terminates via the button and via direct launch like 
~/Downloads/cdto_2_6/terminal/cd\ to.app/Contents/MacOS/cd\ to

**Comment by daviewales** [comment]
I'm on Yosemite, and it's working perfectly.
You should probably include a few more details about your setup.

**Comment by okertanov** [comment]
Thanks.
So I'm doing something wrong... i'll double check it

**Comment by reduxdj** [comment]
Can't drag to toolbar and get working on Yosemite.

**Comment by GeoffreyPlitt** [comment]
Same here

**Comment by gingerbeardman** [comment]
Workaround:

Open two finder windows:
1. any folder—right/option click toolbar and choose "Customize Toolbar..."
2. location of cdto—drag cdto from here to toolbar

**Comment by GeoffreyPlitt** [comment]
Worked perfectly, thanks! We can close this.

**Comment by Finetuned** [comment]
In El Capitan, cmd-drag to the toolbar

**Comment by gingerbeardman** [comment]
Nice!
