### ISSUE TITLE
Nothing opens for iTerm2

### ISSUE THREAD

**Issue by dagoodma** [jbtule/cdto#17]
Hello. When I click the "cd to" icon in finder nothing happens. I dragged "cd to.app" from the iterm folder to my Applications folder, and then added it to the finder toolbar. I am using iTerm2.1, Mac OS X 10.7.5, and have downloaded the latest cdto release as of today. I also tried iTerm2.0. I can also verify that the iterm plugin was the only one when I viewed the "cd to.app" contents.

**Comment by strider72** [comment]
Works for me with iTerm2 version 2.0.0.20141103 on Mac OS 10.10.3.

**Comment by tcyrus** [comment]
Works for me with iTerm version 2.9.20160206 on Mac OS 10.11.3

**Comment by episodeyang** [comment]
also does not work for me.

**Comment by episodeyang** [comment]
Turn out that need to use command drag, instead of command options drag.

**Comment by windhost** [comment]
+1
