### ISSUE TITLE
Should always open to directory?

### ISSUE THREAD

**Issue by strider72** [jbtule/cdto#18]
If I happen to have an app selected, the Terminal opens to the inside of the App ("ls" reveals the "contents" directory of the app).  Yes, I know that technically speaking an app "package" is a disguised directory, but I think this is not really expected behavior.  If I'm in the Applications directory and happen to have an app selected, cdto should open to the Applications directory, not to the contents of the app itself.

**Comment by Michael4824** [comment]
It's strange, I'm having this issue on one of my machines, but not the other.

**Comment by jbtule** [comment]
this is fixed in 3.0 for mac os x mojave and catalina
