### ISSUE TITLE
No Terminal Window Opens on macOS Sierra 10.12.6 (16G29)

### ISSUE THREAD

**Issue by tarheel-achiu** [jbtule/cdto#29]

**Comment by punkratz312** [comment]
works for me.

**Comment by tarheel-achiu** [comment]
What should Nevermidnbe my next step to trouble shoot?

**Comment by tarheel-achiu** [comment]
My mistake. I chose the wrong version off the app

**Comment by dm-grinko** [comment]
+1
I can't get what version should I use as well
