### ISSUE TITLE
Change default window profile

### ISSUE THREAD

**Issue by DeanStern** [jbtule/cdto#32]
How can I change the default opened window profile? If I applied it in the global terminal app settings, it's still opened with the white default profile.

Thanks,
Homebrew lover

**Comment by jbtule** [comment]
While i don't think this happens in current mac os x. You can now set a separate default profile for cd to in v3.1

**Comment by CyanideBoy** [comment]
@jbtule Can you please elaborate on how to do this? I do not know how to set default profile for terminal for cd!
