### ISSUE TITLE
Is it possible to open current director in already opened terminal. 

### ISSUE THREAD

**Issue by shakthydoss** [jbtule/cdto#33]
I already have a terminal opened.  From finder I am clicking the "cdto" icon. is it possible to open the current directory in the already open terminal as new tab.

**Comment by jbtule** [comment]
In PR #42 I'm adding an option to close an automatically opened window, for bug #34, but only auto closing a newly opened empty window is how I'm going to solve it, changing an existing window can't be done in a shell agnostic way.
