### ISSUE TITLE
2 Terminals open on OsX Mojave

### ISSUE THREAD

**Issue by shaikh1110** [jbtule/cdto#34]
When opening cd to, expecting to open terminal at current directory it opens two terminals one with base root and second at current directory

<img width="768" alt="screen shot 2018-09-29 at 11 57 33 am" src="https://user-images.githubusercontent.com/20888676/46242883-ec55c480-c3de-11e8-8c54-b732c7a0b5a1.png">

**Comment by dogatekin** [comment]
I have the same problem. I discovered that this does not happen if you close all your terminal windows by using ⌘W.

**Comment by DmitryZemlyuk** [comment]
Hi. +1 with the same problem. @jbtule can we help with fixes? (send log, anything...)

**Comment by grenappels** [comment]
+1 I also have this problem!

**Comment by jensrutschmann** [comment]
I believe it happens because of this error:
```
Since sending application [sess=100007 pid=98033 uid:501,501,501 g:20,20 pV:396619] is not permitted to send this AppleEvent to this process, returning an errAEEventNotPermitted reply.
```
I see this every time I click the cdto icon in Finder.

Also see https://trac.cyberduck.io/ticket/10475#comment:3

> If you build your app with the 10.14 SDK, the NSAppleEventsUsageDescription key is required. If it is not provided, trying to send an AppleEvent to another, running app will always return error errAEEventNotPermitted (-1743). The key is only optional when using older SDKs.

**Comment by huti26** [comment]
The issue only occurs when you quit Terminal using ⌘Q. If you dont actually quit the application, it should still work.

**Comment by rterrabh** [comment]
I have the same issue in Mac OS 10.14.3.

If terminal is not "active" (open or running without any windows), cd to works perfectly.

However, I always use ⌘Q and two windows are annoying me. Is there any perspective to fix this issue? I can help you @jbtule testing if you want to.

**Comment by williamaeberhard** [comment]
Same here with Mac OS 10.14.3. I confirm that cdto creates that second window only when Terminal has been completely closed beforehand (not running in background). To be clear, one window opens at the default directory (~ for me) and the second one opens wherever cdto was executed from.

**Comment by jakevossen5** [comment]
Confirming this still exists on 10.14.4 (18E226)

**Comment by gingerbeardman** [comment]
I now use https://github.com/Ji4n1ng/OpenInTerminal (Lite version)

**Comment by dogatekin** [comment]
Hey thanks for letting us know, that's great!

**Comment by jbtule** [comment]
Enable this setting
```
defaults write name.tuley.jay.cd-to cdto-close-default-window -bool true
```
And use v3.1 and cd to will now attempt to close the 2nd window.
https://github.com/jbtule/cdto/releases/tag/v3.1
