### ISSUE TITLE
Open current directory in any application

### ISSUE THREAD

**Issue by kheyse** [jbtule/cdto#4]
Hi

I'd like to let you know that I've created a plugin to open the current directory in SourceTree (a git gui client). https://github.com/kheyse/cdto
Maybe you could make cdto into a more general tool that can open the current directory in any application the user wishes (using some sort of config file)?

Anyway, thanks for the tool!

**Comment by jbtule** [comment]
alternative: https://github.com/Ji4n1ng/OpenInTerminal
