### ISSUE TITLE
Does not change folder (iTerm2)

### ISSUE THREAD

**Issue by liuyigh** [jbtule/cdto#41]
Hi, Everyone,

Somehow in my system since longtime ago, clicking the button only open iterm2, but not "cd to" the desired directory. Always the ~ directory. Still the same on Catalina. Using iterm2 3.3.7b1, just switched to Zsh. Was the same with bash.

Thanks! Let me know if you need more info.

**Comment by jbtule** [comment]
sorry, I've dropped the iterm2 version. I don't know yet if any alternatives work yet on catalina.

**Comment by liuyigh** [comment]
Got it. Thanks. I just find that OpenInTerminal also does not work on my iTerm2. It must be some problem of my own iTerm2 settings.

**Comment by liuyigh** [comment]
I finally figured out why. For future references. It 

also applies to OpenInTerminal:

In iTerm2 -> Preferences -> Profiles -> General -> Command, it should be set as "Login Shell", not the default "Command: login -fp $USERNAME".

![ITerm2-Setting](https://user-images.githubusercontent.com/5641850/66678036-d6005c80-ec1f-11e9-880f-cd4dbae6c534.png)

At some release, iTerm2 changed the default option for that.
