### ISSUE TITLE
Release ARM/Intel binary

### ISSUE THREAD

**Issue by jil24** [jbtule/cdto#52]
Seems to recompile just fine for ARM. Can you release a new binary?

**Comment by laffed** [comment]
bump

**Comment by jbtule** [comment]
Is there any issues with the current intel version on ARM? My understanding is that Rossetta2 statically recompiles on first run, so I assumed it was working?

**Comment by faisal** [comment]
The Intel version does work. The Apple silicon version seems to be slightly snappier but that may just be placebo. https://github.com/jbtule/cdto/pull/61 should produce a Universal binary, though.

**Comment by jbtule** [comment]
Released.
