### ISSUE TITLE
Terminal opens but focus shifts to space with open Terminal

### ISSUE THREAD

**Issue by burdges** [jbtule/cdto#7]
If I use a stock install and I click the cdto icon, then it open a Terminal window in my current Space with the current directory, exactly as desired, but Spaces shifts focus to different Terminal window on another Space.  

One can fix this by unchecking "When switching to an application, switch to a space with open windows for the application" in System preferences -> Mission Control, but..
see : https://apple.stackexchange.com/questions/4801/how-can-i-stop-spaces-from-switching-automatically 

It might be worth mentioning this in the documentation or readme or whatever because the default behavior is quite unintuitive.

**Comment by jbtule** [comment]
I think this mac os has changed this in the 5 years since.
